openeuropa/oe_translation

modules/oe_translation_poetry/config/install/tmgmt.translator.poetry.yml
modules/oe_translation_poetry/src/Plugin/tmgmt/Translator/PoetryTranslator.php
modules/oe_translation_poetry/src/Poetry.php
modules/oe_translation_poetry/src/PoetryTranslatorUI.php
modules/oe_translation_poetry/tests/Functional/PoetryMockTest.php

Add empty translator to commence development.
- Added: Add empty translator.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-2157: Starting the Poetry translator plugin.

---

modules/oe_translation_poetry/tests/Kernel/IdentifierTest.php
modules/oe_translation_poetry/tests/Kernel/PoetryRequestIdentifierTest.php

Add tests for identifier generation.

OPENEUROPA-2107: test identifier

---

modules/oe_translation_poetry/modules/oe_translation_poetry_html_formatter/src/PoetryHtmlFormatter.php

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-0000: Fix the html import when dealing with complex strings.

---

modules/oe_translation_poetry/modules/oe_translation_poetry_mock/fixtures/error_template.xml
modules/oe_translation_poetry/modules/oe_translation_poetry_mock/src/Controller/PoetryMockController.php
modules/oe_translation_poetry/modules/oe_translation_poetry_mock/src/PoetryMock.php
modules/oe_translation_poetry/modules/oe_translation_poetry_mock/src/PoetryMockFixturesGenerator.php
modules/oe_translation_poetry/tests/Functional/PoetryMockTest.php

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-2191: Add error support for the poetry mock.

---

src/Plugin/tmgmt/Translator/PermissionTranslator.php

Fix timeline fields in translation forms.

OPENEUROPA-2108: Fix labels in translation form.

---

modules/oe_translation_poetry/modules/oe_translation_poetry_mock/fixtures/translation_template.xml
modules/oe_translation_poetry/modules/oe_translation_poetry_mock/oe_translation_poetry_mock.routing.yml
modules/oe_translation_poetry/modules/oe_translation_poetry_mock/oe_translation_poetry_mock.services.yml
modules/oe_translation_poetry/modules/oe_translation_poetry_mock/src/Controller/PoetryMockController.php
modules/oe_translation_poetry/modules/oe_translation_poetry_mock/src/EventSubscriber/ContentTranslationOverviewAlterSubscriber.php
modules/oe_translation_poetry/modules/oe_translation_poetry_mock/src/PoetryMockFixturesGenerator.php
modules/oe_translation_poetry/src/EventSubscriber/PoetryNotificationSubscriber.php
modules/oe_translation_poetry/src/Form/PoetryCheckoutFormBase.php
modules/oe_translation_poetry/src/Plugin/tmgmt/Translator/PoetryTranslator.php
oe_translation.services.yml
src/Controller/ContentTranslationController.php
src/Event/ContentTranslationOverviewAlterEvent.php
src/EventSubscriber/TranslationOverviewRequestSubscriber.php
tests/features/local_translations.feature

Aside from the UI for mocks, I also fixed the issue with requesting translations from incorrect source languages.

OPENEUROPA-2230 - UI for mocking requests.

---

.drone.yml
behat.yml.dist
composer.json
config/install/user.role.translator.yml
modules/oe_translation_poetry/README.md
modules/oe_translation_poetry/oe_translation_poetry.module
modules/oe_translation_poetry/src/JobItemListBuilder.php
modules/oe_translation_poetry/src/Plugin/tmgmt/Translator/PoetryTranslator.php
modules/oe_translation_poetry/src/Poetry.php
modules/oe_translation_poetry/src/PoetryTranslatorUI.php
modules/oe_translation_poetry/tests/Functional/PoetryNotificationTest.php
modules/oe_translation_poetry/tests/Functional/PoetryTranslationTestBase.php
modules/oe_translation_poetry/tests/Traits/PoetryTestTrait.php
runner.yml.dist
tests/Behat/CleanupContext.php
tests/Behat/PoetryTranslationContext.php
tests/features/poetry_translations.feature

* Cleaned up a bit the TMGMT job UIs to make it clearer to approve a translation
* Access to the translator role to approve jobs

OPENEUROPA-2230: Clean translation review for translators.

---

modules/oe_translation_poetry/config/install/tmgmt.translator.poetry.yml
modules/oe_translation_poetry/modules/oe_translation_poetry_mock/src/Controller/PoetryMockController.php
modules/oe_translation_poetry/src/EventSubscriber/PoetryNotificationSubscriber.php
modules/oe_translation_poetry/src/Form/PoetryCheckoutFormBase.php
modules/oe_translation_poetry/src/Plugin/tmgmt/Translator/PoetryTranslator.php
modules/oe_translation_poetry/tests/Functional/PoetryNotificationTest.php

OPENEUROPA-2284: Map Drupal languages to Poetry languages

---

CHANGELOG.md

Update changelog for release 0.1.1.

OPENEUROPA-1766: Release 0.1.1.

---

modules/oe_translation_poetry/src/EventSubscriber/PoetryNotificationSubscriber.php
modules/oe_translation_poetry/tests/Functional/PoetryNotificationTest.php
modules/oe_translation_poetry/tests/Traits/PoetryTestTrait.php

Use items from job instead of items from received translation.

OPENEUROPA-2462: Fix secondary translations

---

modules/oe_translation_poetry/oe_translation_poetry.module
modules/oe_translation_poetry/src/Plugin/tmgmt/Translator/PoetryTranslator.php
oe_translation.module
src/Access/JobAccessHandler.php
src/JobAccessTranslatorInterface.php
src/Plugin/tmgmt/Translator/PermissionTranslator.php
tests/features/local_translations.feature

* Show a user warning when trying to delete a translation job that is ongoing in Poetry.
* Allow local translation jobs to be deleted.

OPENEUROPA-2276: Various small improvements.

---

modules/oe_translation_poetry/src/Plugin/tmgmt/Translator/PoetryTranslator.php
modules/oe_translation_poetry/tests/Functional/PoetryTranslationRequestTest.php
tests/features/poetry_translations.feature

Hide request button while translations are not received (temporary solution).

OPENEUROPA-2551 - Hide/show request button depending on the translation status

---

CHANGELOG.md

Prepare release 0.2
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 0.2

---

CHANGELOG.md
composer.json

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-0000: Preparing for release.

---

modules/oe_translation_poetry/src/Form/NewTranslationRequestForm.php

Change return action to UPDATE, for new requests and update requests.
- Added: test for message
- Changed: Return action from INSERT to UPDATE

OPENEUROPA-2784: Change return action to UPDATE.

---

modules/oe_translation_poetry/src/Plugin/tmgmt/Translator/PoetryTranslator.php
tests/Behat/PoetryTranslationContext.php
tests/features/poetry_translations.feature

Add request reference info on top of the overview translation page.

OPENEUROPA-2696: Add request reference info in overview page.

---

README.md
composer.json
modules/oe_translation_block_field/README.md
modules/oe_translation_block_field/oe_translation_block_field.info.yml
modules/oe_translation_block_field/oe_translation_block_field.module
modules/oe_translation_block_field/src/BlockFieldProcessor.php
modules/oe_translation_block_field/tests/Kernel/BlockFieldTest.php
runner.yml.dist

Submodule that integrates with the Block Field module and makes the block reference field translatable.

OPENEUROPA-2752: BlockField TMGMT processor.

---

composer.json
modules/oe_translation_block_field/README.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-0002: Removing block_field from dependency list.

---

src/Plugin/tmgmt/Translator/PermissionTranslator.php

OPENEUROPA-2608: Generate new breadcrumb only if entity exists.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Update changelog for release 0.5.0.

---

CHANGELOG.md

Update changelog for release 0.6.0. 
- Added:
- Changed: Update changelog for release 0.6.0. 
- Deprecated: 
- Removed:
- Fixed:
- Security:
```sh
```

OPENEUROPA-3017: Prepare release 0.6.0.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

RELEASE-0.8.0: Update CHANGELOG.md for release 0.8.0.

---

docker-compose.yml

Remove test env variable.
- Added:
- Changed: Remove test env variable.
- Deprecated: 
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-545: Remove test env variable.

---

.gitignore
composer.json

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-529: Replace scaffold library.

---

CHANGELOG.md

Update changelog for release 0.10.0.
- Added:
- Changed: Update changelog for release 0.10.0.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 0.10.0.

---

src/Plugin/tmgmt/Translator/PermissionTranslator.php
tests/Functional/LocalTranslationTest.php

The first commit has the failing test while the second brings the fix.

EWPP-706: Fixing type hint that assumes local translations work with Node only.

---

CHANGELOG.md

Prepare release 0.13.0.
- Added:
- Changed: Update changelog for release 0.13.0
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 0.13.0.

---

modules/oe_translation_poetry/oe_translation_poetry.info.yml
modules/oe_translation_poetry/tests/Functional/PoetryConfigurationTest.php
modules/oe_translation_poetry/tests/Functional/PoetryMockTest.php

Remove dblog dependency.
- Added:
- Changed:
- Deprecated:
- Removed: Remove dblog dependency.
- Fixed:
- Security:
```sh
```

EWPP-124: Remove dblog dependency.

---

CHANGELOG.md

Update changelog for relase 0.15.0.
- Added:
- Changed: Update changelog for relase 0.15.0.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare relase 0.15.0.

---

CHANGELOG.md

Prepare release 0.16.1.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 0.16.1.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-0000: Prepare for 0.17.0 release.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 0.17.1.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 0.18.0.

---

composer.json

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-0000: Remove conflict with oe_editorial.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

EWPP-0000: Prepare for 0.18.1 release.

---

CHANGELOG.md

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```

Prepare release 0.19.0.
